### ISSUE TITLE
RoundChangeLifecycleStageEvent to implement the cancellable interface

### ISSUE THREAD

**Issue by KieronWiltshire** [caseif/Flint#20]
### Proposal

The [RoundChangeLifecycleStageEvent](https://github.com/caseif/Flint/blob/master/src/main/java/net/caseif/flint/event/round/RoundChangeLifecycleStageEvent.java) event should implement the `cancellable` interface in order to prevent the round from crossing over to the next stage in the life cycle. The current API restricts a stage to a single state of completion, this being the specified duration of time. It may be a need for some to perform other checks in order to determine whether or not the life cycle is completed.

### Consider this scenarios
> You have a stage in your life cycle called "Lobby". During this stage, you may want to perform a check to determine the number of players that have currently joined the round. If the number of players are less than 6, you wish to reset the lobby timer, and wait for more players.

### Conclusion

Making this simple adjustment to the API would allow these types of scenarios to be carried out with very little effort.

**Comment by caseif** [comment]
Issue text merged into #21.
